ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.fintech.loan.ApplicationKt.main ]
    }
    resilience4j {
        circuitbreaker {
            instances {
                riskEvaluationCircuitBreaker {
                    failureRateThreshold = 50
                    waitDurationInOpenState = 60000
                    permittedNumberOfCallsInHalfOpenState = 3
                    automaticTransitionFromOpenToHalfOpenEnabled = true
                }
            }
        }
    }
}